### ISSUE TITLE
StandardSqlDataType' has no attribute 'STRING'

### ISSUE THREAD

**Issue by FinnFrotscher** [adswerve/target-bigquery#24]
Trying to pipe from `tap-hubspot` to `target-bigquery` results in the following issue on the following tables:
      
```
      - workflows.*
      - contact_lists.*
      - deal_pipelines.*
      - contacts_by_company.*
      - email_events.*
```

```
Traceback (most recent call last):
  File "/Users/finn/code/[]/bi/meltano/.meltano/loaders/target-bigquery--hubspot/venv/bin/target-bigquery", line 5, in <module>
    from target_bigquery import main
  File "/opt/homebrew/Caskroom/miniconda/base/envs/bi/lib/python3.6/site-packages/target_bigquery/__init__.py", line 12, in <module>
   
   [....]
   
    "STRING": types.StandardSqlDataType.STRING,
AttributeError: type object 'StandardSqlDataType' has no attribute 'STRING'
```

**Comment by RuslanBergenov** [comment]
My coworker has worked with tap-hubspot. He did have some issues with some of the catalog schemas, so he removed them for our use case. We suspect that the root cause of your issues might be related to tap-hubspot too.

**Comment by RuslanBergenov** [comment]
Hi @FinnFrotscher , I'll close this issue due to the inactivity, please please feel free to respond here, we'll reopen it.
