### ISSUE TITLE
tap-hubspot KeyError: 'RECORD' error

### ISSUE THREAD

**Issue by RuslanBergenov** [adswerve/target-bigquery#34]
A user reached out to us directly via Meltano Slack workspace and reported this error.

They are using tap-hubspot. 

I'm assisting the user via Slack, investigating the error, trying to figure out if there are some issues in the input JSON schema or a bug in target-bigquery. 

```
2022-04-07T16:37:36.333692Z [info     ] INFO Syncing contact_lists     cmd_type=extractor job_id=staging_hubspot-to-bigquery name=tap-hubspot run_id=928af32c-b08e-4433-9589-b55f7f83f119 stdio=stderr
2022-04-07T16:37:36.333825Z [info     ] INFO sync_contact_lists from 2015-03-02T00:00:00Z cmd_type=extractor job_id=staging_hubspot-to-bigquery name=tap-hubspot run_id=928af32c-b08e-4433-9589-b55f7f83f119 stdio=stderr
2022-04-07T16:37:36.334073Z [info     ] INFO Updating state with {'currently_syncing': 'contact_lists', 'bookmarks': {'owners': {'updatedAt': '2022-04-07T13:04:36.409000Z'}, 'meetings': {'current_sync_start': '2022-04-07T15:17:23.556704Z', 'updatedAt': '2022-04-07T15:15:04.566000Z'}, 'forms': {'updatedAt': '2021-08-04T20:28:08.385000Z'}, 'workflows': {'updatedAt': '2022-03-31T21:38:40.216000Z'}}} cmd_type=loader job_id=staging_hubspot-to-bigquery name=target-bigquery run_id=928af32c-b08e-4433-9589-b55f7f83f119 stdio=stderr
2022-04-07T16:37:36.334260Z [info     ] INFO GET https://api.hubapi.com/contacts/v1/lists?count=250 cmd_type=extractor job_id=staging_hubspot-to-bigquery name=tap-hubspot run_id=928af32c-b08e-4433-9589-b55f7f83f119 stdio=stderr
2022-04-07T16:37:36.334372Z [info     ] INFO contact_lists schema: {'type': 'object', 'properties': {'parentId': {'type': ['null', 'integer']}, 'metaData': {'type': 'object', 'properties': {'processing': {'type': ['null', 'string']}, 'size': {'type': ['null', 'integer']}, 'error': {'type': ['null', 'string']}, 'lastProcessingStateChangeAt': {'type': ['null', 'string'], 'format': 'date-time'}, 'lastSizeChangeAt': {'type': ['null', 'string'], 'format': 'date-time'}}}, 'dynamic': {'type': ['null', 'boolean']}, 'name': {'type': ['null', 'string']}, 'filters': {'type': 'array', 'items': {'type': 'array', 'items': {'type': 'object', 'properties': {'filterFamily': {'type': ['null', 'string']}, 'withinTimeMode': {'type': ['null', 'string']}, 'checkPastVersions': {'type': ['null', 'boolean']}, 'type': {'type': ['null', 'string']}, 'property': {'type': ['null', 'string']}, 'value': {'type': ['null', 'string']}, 'operator': {'type': ['null', 'string']}}}}}, 'portalId': {'type': ['null', 'integer']}, 'createdAt': {'type': ['null', 'string'], 'format': 'date-time'}, 'listId': {'type': ['null', 'integer']}, 'updatedAt': {'type': ['null', 'string'], 'format': 'date-time'}, 'internalListId': {'type': ['null', 'integer']}, 'readOnly': {'type': ['null', 'boolean']}, 'deleteable': {'type': ['null', 'boolean']}, 'listType': {'type': ['null', 'string']}, 'archived': {'type': ['null', 'boolean']}}} cmd_type=loader job_id=staging_hubspot-to-bigquery name=target-bigquery run_id=928af32c-b08e-4433-9589-b55f7f83f119 stdio=stderr
2022-04-07T16:37:37.262097Z [info     ] INFO METRIC: {"type": "timer", "metric": "http_request_duration", "value": 0.9272665977478027, "tags": {"endpoint": "contacts", "http_status_code": 200, "status": "succeeded"}} cmd_type=extractor job_id=staging_hubspot-to-bigquery name=tap-hubspot run_id=928af32c-b08e-4433-9589-b55f7f83f119 stdio=stderr
2022-04-07T16:37:37.264290Z [info     ] CRITICAL 'RECORD'              cmd_type=loader job_id=staging_hubspot-to-bigquery name=target-bigquery run_id=928af32c-b08e-4433-9589-b55f7f83f119 stdio=stderr
2022-04-07T16:37:37.264647Z [info     ] CRITICAL ['Traceback (most recent call last):\n', '  File "/home/stephane/Documents/projects/meltano-projects/meltano/.meltano/loaders/target-bigquery/venv/lib/python3.9/site-packages/target_bigquery/__init__.py", line 129, in main\n    for state in state_iterator:\n', '  File "/home/stephane/Documents/projects/meltano-projects/meltano/.meltano/loaders/target-bigquery/venv/lib/python3.9/site-packages/target_bigquery/process.py", line 54, in process\n    for s in handler.handle_record_message(msg):\n', '  File "/home/stephane/Documents/projects/meltano-projects/meltano/.meltano/loaders/target-bigquery/venv/lib/python3.9/site-packages/target_bigquery/processhandler.py", line 179, in handle_record_message\n    nr = format_record_to_schema(nr, self.bq_schema_dicts[stream])\n', '  File "/home/stephane/Documents/projects/meltano-projects/meltano/.meltano/loaders/target-bigquery/venv/lib/python3.9/site-packages/target_bigquery/schema.py", line 441, in format_record_to_schema\n    record[k] = [conversion_dict[bq_schema[k]["type"]](vi) for vi in v]\n', '  File "/home/stephane/Documents/projects/meltano-projects/meltano/.meltano/loaders/target-bigquery/venv/lib/python3.9/site-packages/target_bigquery/schema.py", line 441, in <listcomp>\n    record[k] = [conversion_dict[bq_schema[k]["type"]](vi) for vi in v]\n', "KeyError: 'RECORD'\n"] cmd_type=loader job_id=staging_hubspot-to-bigquery name=target-bigquery run_id=928af32c-b08e-4433-9589-b55f7f83f119 stdio=stderr
2022-04-07T16:37:37.278640Z [info     ] INFO GET https://api.hubapi.com/contacts/v1/lists?count=250&offset=250 cmd_type=extractor job_id=staging_hubspot-to-bigquery name=tap-hubspot run_id=928af32c-b08e-4433-9589-b55f7f83f119 stdio=stderr
2022-04-07T16:37:37.305534Z [error    ] Loading failed                 code=2 job_id=staging_hubspot-to-bigquery message=CRITICAL ['Traceback (most recent call last):\n', '  File "/home/stephane/Documents/projects/meltano-projects/meltano/.meltano/loaders/target-bigquery/venv/lib/python3.9/site-packages/target_bigquery/__init__.py", line 129, in main\n    for state in state_iterator:\n', '  File "/home/stephane/Documents/projects/meltano-projects/meltano/.meltano/loaders/target-bigquery/venv/lib/python3.9/site-packages/target_bigquery/process.py", line 54, in process\n    for s in handler.handle_record_message(msg):\n', '  File "/home/stephane/Documents/projects/meltano-projects/meltano/.meltano/loaders/target-bigquery/venv/lib/python3.9/site-packages/target_bigquery/processhandler.py", line 179, in handle_record_message\n    nr = format_record_to_schema(nr, self.bq_schema_dicts[stream])\n', '  File "/home/stephane/Documents/projects/meltano-projects/meltano/.meltano/loaders/target-bigquery/venv/lib/python3.9/site-packages/target_bigquery/schema.py", line 441, in format_record_to_schema\n    record[k] = [conversion_dict[bq_schema[k]["type"]](vi) for vi in v]\n', '  File "/home/stephane/Documents/projects/meltano-projects/meltano/.meltano/loaders/target-bigquery/venv/lib/python3.9/site-packages/target_bigquery/schema.py", line 441, in <listcomp>\n    record[k] = [conversion_dict[bq_schema[k]["type"]](vi) for vi in v]\n', "KeyError: 'RECORD'\n"] name=meltano run_id=928af32c-b08e-4433-9589-b55f7f83f119
2022-04-07T16:37:37.305950Z [info     ] ELT could not be completed: Loader failed. cmd_type=elt job_id=staging_hubspot-to-bigquery name=meltano run_id=928af32c-b08e-4433-9589-b55f7f83f119 stdio=stderr
2022-04-07T16:37:37.306068Z [info     ] For more detailed log messages re-run the command using 'meltano --log-level=debug ...' CLI flag. cmd_type=elt job_id=staging_hubspot-to-bigquery name=meltano run_id=928af32c-b08e-4433-9589-b55f7f83f119 stdio=stderr
2022-04-07T16:37:37.306146Z [info     ] Note that you can also check the generated log file at '/home/stephane/Documents/projects/meltano-projects/meltano/.meltano/logs/elt/staging_hubspot-to-bigquery/928af32c-b08e-4433-9589-b55f7f83f119/elt.log'. cmd_type=elt job_id=staging_hubspot-to-bigquery name=meltano run_id=928af32c-b08e-4433-9589-b55f7f83f119 stdio=stderr
2022-04-07T16:37:37.306203Z [info     ] For more information on debugging and logging: https://docs.meltano.com/reference/command-line-interface#debugging cmd_type=elt job_id=staging_hubspot-to-bigquery name=meltano run_id=928af32c-b08e-4433-9589-b55f7f83f119 stdio=stderr
ELT could not be completed: Loader failed.
For more detailed log messages re-run the command using 'meltano --log-level=debug ...' CLI flag.
Note that you can also check the generated log file at '/home/stephane/Documents/projects/meltano-projects/meltano/.meltano/logs/elt/staging_hubspot-to-bigquery/928af32c-b08e-4433-9589-b55f7f83f119/elt.log'.
For more information on debugging and logging: https://docs.meltano.com/reference/command-line-interface#debugging
2022-04-07T16:37:37.346551Z [error    ] Future exception was never retrieved
future: <Future finished exception=BrokenPipeError()> 
```

**Comment by RuslanBergenov** [comment]
We helped the open source member solve the issue. It wasn't a bug in target-bigquery per se. 

Solution notes are below. Credit: Robert Kraševec.

We actually had this exact same issue in January 2021.

It has to do with the weird field `"filters"` inside `contact_lists `stream in tap-hubspot.

When we look at the data, field `"filters"` is a list of lists of dict, example:

```
[
  [
    {...}
  ],
  [
    {...}
  ],
  [
    {...}
  ]
]
```
We were having a really hard time loading this into BigQuery.

We only succeeded when we forced it to be an array of strings, by changing tap-catalog.json and supplying that tap-catalog while running the sync. 

The solution is to do this:
1. set `"filters"` field schema in tap-catalog.json like this:

```
"filters": {
                        "type": [
                            "null",
                            "array"
                        ],
                        "items": {
                            "type": [
                                "null",
                                "string"
                            ]
                        }
                    },
```
2. supply this tap-catalog.json during the sync
