### ISSUE TITLE
I got an error while using target-bigquery

### ISSUE THREAD

**Issue by hoangson101197** [adswerve/target-bigquery#4]
INFO Beginning sync for InnoDB table m5.orders
INFO Stream orders is using incremental replication
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\Scripts\target-bigquery.exe\__main__.py", line 4, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\target_bigquery\__init__.py", line 12, in <module>
    from target_bigquery.process import process
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\target_bigquery\process.py", line 12, in <module>
    from target_bigquery.schema import build_schema, filter
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\target_bigquery\schema.py", line 4, in <module>
    from google.cloud.bigquery import SchemaField
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\google\cloud\bigquery\__init__.py", line 35, in <module>
    from google.cloud.bigquery.client import Client
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\google\cloud\bigquery\client.py", line 50, in <module>
    import google.cloud._helpers
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\google\cloud\_helpers.py", line 33, in <module>
    from google.protobuf import duration_pb2
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\google\protobuf\duration_pb2.py", line 5, in <module>
    from google.protobuf import descriptor as _descriptor
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\google\protobuf\descriptor.py", line 48, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.
INFO METRIC: {"type": "timer", "metric": "job_duration", "value": 0.19600915908813477, "tags": {"job_type": "sync_table", "database": "m5", "table": "orders", "status": "failed"}}
CRITICAL [Errno 32] Broken pipe
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\Scripts\tap-mysql.exe\__main__.py", line 7, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\singer\utils.py", line 229, in wrapped
    return fnc(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\tap_mysql\__init__.py", line 732, in main
    do_sync(mysql_conn, args.config, catalog, state)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\tap_mysql\__init__.py", line 679, in do_sync
    sync_non_binlog_streams(mysql_conn, non_binlog_catalog, config, state)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\tap_mysql\__init__.py", line 654, in sync_non_binlog_streams
    do_sync_incremental(mysql_conn, catalog_entry, state, columns, optional_limit)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\tap_mysql\__init__.py", line 521, in do_sync_incremental
    bookmark_properties=[replication_key])
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\tap_mysql\__init__.py", line 507, in write_schema_message
    bookmark_properties=bookmark_properties
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\singer\messages.py", line 227, in write_message
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='cp1252'>
OSError: [Errno 22] Invalid argument

**Comment by zvizdo** [comment]
Seems like it could be a catalog related issue. Are you able to share the catalog for the stream?

**Comment by hoangson101197** [comment]
Looks like the error occurred on singer-python when using it on a window server. I have a similar question on StackOverflow:
[](https://stackoverflow.com/questions/65698335/singer-io-oserror-errno-22-invalid-argument-when-use-tap-postgres-with-targ?noredirect=1#comment116160730_65698335)

Here are my properties:
![image](https://user-images.githubusercontent.com/20607438/104671996-81e10380-5711-11eb-9111-378f0c64692d.png)

**Comment by Jake8K** [comment]
Are you able to share the file?

**Comment by zvizdo** [comment]
Closing due to inactivity.
